version: '3.7'
services:
  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    entrypoint: /entrypoint.sh
    ports:
      - 8000:8000
    environment:
      - DJANGO_SUPERUSER_PASSWORD=12345678
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@djangotest.com
    depends_on:
      - postgres
      - redis
  celery:
    build: .
    command: celery -A django_test worker --beat -l info
    depends_on:
      - postgres
      - redis
      - django
  postgres:
    image: postgres:12.0-alpine
    environment:
      - POSTGRES_PASSWORD=django_test
      - POSTGRES_USER=django_test
      - POSTGRES_DB=django_test
  redis:
    image: redis:6.0.5-alpine
