# Generated by Django 3.0.8 on 2020-07-13 11:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('internal_id', models.IntegerField(unique=True)),
                ('function_code', models.TextField()),
                ('status', models.TextField(choices=[('evaluation', 'Evaluation'), ('correct', 'Correct'), ('wrong', 'Wrong')], default='evaluation')),
            ],
        ),
    ]
