# Generated by Django 3.0.8 on 2020-07-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200713_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='internal_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
